### ISSUE TITLE
SyncReleases Support

### ISSUE THREAD

**Issue by JKSnd** [phillipsj/Cake.Squirrel#16]
I'm evaluating this add in to potentially replace the powershell based deployment script I use. Part of my powershell script is syncing the local Releases with the one on the deployment server.

Supporting the SyncReleases operation in this addin would be pretty slick.

**Comment by phillipsj** [comment]
Awesome, I will take a look and see what is required to add the functionality.  Is this something you would like to try to do?

**Comment by JKSnd** [comment]
Well this would be my first foray into writing for a cake add-in. But I'll give it a shot!

**Comment by phillipsj** [comment]
I have some tutorials on my blog here
http://www.phillipsj.net/tags/tutorials.

Take a look and if you think it's too much just let me know.   I just
didn't want to take the opportunity away if you wanted to try.

**Comment by JKSnd** [comment]
Cool, I had a look at the repo and your tutorials. I found myself spending too much time trying to figure out how to incorporate this feature since SyncReleases isn't a CLI option for Squirrel.exe, but rather its own executable. I've decided that for now I'll include squirrel.windows as a tool in my cake script and start there.

I would be interested to keep an eye on how you would go about adding this feature, if you decide to though.

**Comment by phillipsj** [comment]
Sure I will right up up as I do it.

**Comment by phillipsj** [comment]
@JKSnd I have added the requested functionality.  You should be able to test by doing the following:

    #addin nuget:https://www.myget.org/F/cake-contrib/api/v2?package=Cake.Squirrel&prerelease

Please try it out and let me know if that works as expected.  Once you do, I will do a release to nuget.  I also wrote a quick [post](http://www.phillipsj.net/posts/cake-contributing-to-an-addin) about my decisions and how I did it.

**Comment by JKSnd** [comment]
Excellent! Thanks for doing that. I'll evaluate in the next couple days once I've cleared some items out of my work stream.

**Comment by JKSnd** [comment]
Just read through the article. I really appreciate that you took the time to explain the work you did to implement this feature. The detail was excellent and the article even filled in some general Cake questions I had. Mad respect.

**Comment by JKSnd** [comment]
Looking pretty good so far. Before I say "ship it!" I'm just working with handling the case when there is no RELEASES file available on the server. I'm pretty sure this is a me-thing, not an issue with the add-in, but I just want to be sure.

**Comment by JKSnd** [comment]
Here's the Task I'm using to evaluate this feature. The try/catch is all about handling the case where there is no RELEASES file on the server yet. Also, I'm using whatever version of squirrel that the project is using, to make sure that deployment and runtime versions of squirrel are the same.

```
Task (Tasks.SyncReleases)
    .IsDependentOn (Tasks.Restore)
    .Does (() => {
        var deploymentUrl = "<REDACTED: super secret server url>";
        try {
            var syncReleasesSettings = new SyncReleasesSettings {
            ToolPath = GetFiles ("../libraries/NuGet/squirrel*/tools/SyncReleases.exe").Single (),
            Url = deploymentUrl
            };

            SyncReleases (syncReleasesSettings);
        } catch(CakeException e) {
            Information ("RELEASES file not found at " + deploymentUrl + ". Assuming this is the first release to this location.");
        }
    });
```
Works like a charm!

Any thoughts? I'm typically not a fan of using try/catch for program flow. Maybe a "TrySyncReleases" overload that returns a status would be useful? maybe with a signature like...

`  public static bool TrySyncReleases(this ICakeContext context, SyncReleasesSettings settings) `

... would help avoid this ugly try/catch pattern?

**Comment by phillipsj** [comment]
I think I should just handle that in the runner if possible.  I will see
what I can do.

**Comment by JKSnd** [comment]
So the latest pushes to develop broke our build process because
#addin nuget:https://www.myget.org/F/cake-contrib/api/v2?package=Cake.Squirrel&prerelease
doesn't pin to a specific version. We're also prevented from updating to Cake.Core >= 0.22.0 beacuse the AssemblyInfoReflector addin is super stale.

Is there a way to pin to a particular commit, or is your myget feed not that granular?

**Comment by phillipsj** [comment]
I am so sorry.  You should be able to pin to a version.  I will post the
syntax and the version for you soon.  I will see what I can do to get an
official package out for you.

**Comment by JKSnd** [comment]
Thank you!!!

**Comment by phillipsj** [comment]
@JKSnd It has been published.  It should be on NuGet within the hour as version 0.12.0.
