### ISSUE TITLE
Add NoDelta flag

### ISSUE THREAD

**Issue by AleksandarDev** [phillipsj/Cake.Squirrel#18]
Can we add no-delta flag to the args? 

I can make PR if you approve.

**Comment by phillipsj** [comment]
@AleksandarDev I would be happy to accept a PR.  Please work on a feature branch of develop.

**Comment by gep13** [comment]
@phillipsj while I am here...

Technically, from a Semantic Version point of view, an improvement should bump the minor version number, not the patch number.  i.e. this should go out on the 0.12.0 release.

**Comment by phillipsj** [comment]
Yep my bad.
