### ISSUE TITLE
Add ArgumentCustomization

### ISSUE THREAD

**Issue by AleksandarDev** [phillipsj/Cake.Squirrel#19]
We should add ArgumentCustomization to settings.

http://cakebuild.net/api/Cake.Core.Tooling/ToolSettings/50AAB3A8

I can make PR if you approve.

**Comment by gep13** [comment]
@AleksandarDev both Settings classes for Cake.Squirrel already derive from ToolSettings, so they should both already have access to the ArgumentCustomization method.  i.e. There should be no need for a PR, as it will already work.

**Comment by AleksandarDev** [comment]
@gep13 Great thanks.

Strange it is not shown in documentation... http://cakebuild.net/api/Cake.Squirrel/SquirrelSettings/

**Comment by gep13** [comment]
@AleksandarDev hmm, that is interesting!  As you can see, on otehr Settings classes it does appear:

http://cakebuild.net/api/Cake.Common.Tools.Chocolatey.Install/ChocolateyInstallSettings/

@daveaglick do you have any ideas as to why it isn't appearing here for the SquirrelSettings class?

**Comment by phillipsj** [comment]
@gep13 LOL, again.
