### ISSUE TITLE
Change Squirrel Alias to Releasify

### ISSUE THREAD

**Issue by phillipsj** [phillipsj/Cake.Squirrel#20]
This will be a multistep change as I will mark the current aliases as obsolete and add in the ones for Releasify.  Then eventually remove Squirrel.

**Comment by gep13** [comment]
@phillipsj what am I missing here?  What is Releasify?  And how does it relate to Squirrel?

**Comment by phillipsj** [comment]
@gep13 It was brought to my attention when the request for SyncReleases support was added that it may make more sense to name the Squirrel Alias Releasify since that is the command that actually is executed. This also opens up the ability to add additional command support more easily.  

If you have any thoughts on the topic it would be great.  It isn't much different than how ChocoInstall vs ChocoUpdate type functionality.

**Comment by gep13** [comment]
@phillipsj ah, I see.

Yes, that makes sense.  Can you use Releasify without Squirrel?  i.e. would it make sense to be a seperate Addin?  Or are they both linked?  If so, renaming the alias to match the underlying tool would be the best option as you suggested here.

**Comment by phillipsj** [comment]
@gep13  It may not make sense in this context as the other commands available from Squirrel.exe are mainly related to actually using Squirrel in the context of an App.  

The releasify command is part of the Squirrel.exe, so I think it should probably stay as it is as that is the only command that has any use from Cake.

**Comment by phillipsj** [comment]
Going to close this after thinking through it.
