### ISSUE TITLE
The name 'GetFile' does not exist in the current context

### ISSUE THREAD

**Issue by dchaib** [phillipsj/Cake.Squirrel#22]
I have tried to add the following code to a task:
```cs
Squirrel(GetFile(path));
```
It didn't work and I kept having the following error:

> Error occurred when compiling build script: E:/Dev/build.cake(73,18): error CS0103: The name 'GetFile' does not exist in the current context

I have managed to make it work with this code though:
```cs
Squirrel(new FilePath(path));
```

Have I done something wrong or is the documentation out of date?

**Comment by phillipsj** [comment]
It is out of date.  That is for the issue and I will get it all updated.

**Comment by dchaib** [comment]
Thanks for the reply. If you want, I cannot have a look and make a pull request.

Also, wouldn't be easier to just use a string as a parameter? That's how it is usually done, isn't it?

**Comment by phillipsj** [comment]
You should be able to use this too.  Using a strong introduces other headaches like full path, working directory type issues. 
  https://cakebuild.net/api/Cake.Common.IO/FileAliases/E00B28C4.
