### ISSUE TITLE
Cake.Core reference is to 0.22.2

### ISSUE THREAD

**Issue by delradie** [phillipsj/Cake.Squirrel#27]
Hi

The current build of Cake.Squirrel.dll (nugget v0.12.0, assembly version 0.9.0.0) references v0.22.2 of Cake.Core, and so is causing assembly verification errors when we update to core version 0.26.0

**Comment by phillipsj** [comment]
I am going to get a new version published today.

**Comment by phillipsj** [comment]
It has been merged in, just need to get it published.

**Comment by delradie** [comment]
Thanks. I'm hoping that with this I can get our build infrastructure updated and fingers crossed fix a major issue our build script (nothing to do with your module, don't worry :) ). Keep up the good work

**Comment by phillipsj** [comment]
It should be live on Nuget now. Thanks for the kind words.
