### ISSUE TITLE
Silent flag has no effect?

### ISSUE THREAD

**Issue by AnderssonPeter** [phillipsj/Cake.Squirrel#3]
I'm currently getting a `Error: Squirrel: Process returned an error (exit code -1).` so i tried to set `Silent = false` to get the output and figure out what's wrong but it had no effect?

**Comment by AnderssonPeter** [comment]
If anyone else needs to figure out the error you can check `tools\squirrel.windows\tools\SquirrelSetup.log`.

**Comment by phillipsj** [comment]
I am looking into this issue, thanks for reporting.

**Comment by phillipsj** [comment]
@AnderssonPeter The silent flag is for setting if the install should be silent, not the Squirrel.exe.  Here is the info from their documentation:   

-s, --silent               Silent install

**Comment by phillipsj** [comment]
So it seems I can use process settings to redirect standard out and to set the error to silent as expected. 
I just need to implement these in the settings or allow users to pass these into an overload which may be the best solution for now.  

 https://github.com/cake-build/cake/blob/develop/src/Cake.Core/IO/ProcessSettings.cs
