### ISSUE TITLE
Update to new Squirrel version

### ISSUE THREAD

**Issue by Slesa** [phillipsj/Cake.Squirrel#30]
Hi,
would be nice to see Squirrel output in Cake, too, no doubt about that.

"Cake is referencing an older version of Cake.Core (0.26.1).
For best compatibility it should target Cake.Core version 0.28.0." - so it may should be updated.

**Comment by phillipsj** [comment]
I will be updating it this week.

**Comment by gep13** [comment]
Just in time for Hacktoberfest! 😄

**Comment by phillipsj** [comment]
LOL, it has been on my list. But yes good timing.

**Comment by phillipsj** [comment]
New version has been published.
